//! Live preview routes.
//!
//! Two distinct route groups:
//!
//! **Server preview** (`/preview/`):
//! - GET /preview/:slug              — iframe wrapper page
//! - GET /preview/:slug/proxy/       — reverse proxy root
//! - GET /preview/:slug/proxy/*path  — reverse proxy subpath
//!
//! **Markdown preview** (`/md-preview/`):
//! - GET /md-preview/:slug           — rendered markdown page
//!
//! Slugs are short-lived (5 min) and generated by the `preview_start` /
//! `md_preview` MCP tools. The slug itself acts as authentication.

use axum::{
    extract::Path,
    http::StatusCode,
    response::Response,
};
use axum::body::Body;

use common::preview_entries::PreviewKind;

// ===========================================================================
// Server preview — iframe wrapper + reverse proxy
// ===========================================================================

/// GET /preview/:slug — iframe wrapper page.
pub async fn wrapper_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(&slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    let remaining_ms = remaining_millis(&entry);
    let title = escape_html(&entry.title);
    let proxy_src = format!("/preview/{}/proxy/", slug);

    let toolbar = toolbar_and_timer(
        &title,
        remaining_ms,
        r#"<button onclick="document.querySelector('iframe').src=document.querySelector('iframe').src">Refresh</button>"#,
    );
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview — {title}</title>
<style>
  {toolbar_css}
  body {{ background: #111; }}
  iframe {{
    width: 100%;
    height: calc(100vh - 40px);
    border: 0;
    background: #fff;
  }}
</style>
</head>
<body>
{toolbar}
<iframe src="{proxy_src}"></iframe>
</body>
</html>"#,
        title = title,
        toolbar_css = TOOLBAR_CSS,
        toolbar = toolbar,
        proxy_src = proxy_src.replace('"', "&quot;"),
    );
    Ok(html_response(html))
}

/// GET /preview/:slug/proxy/ — reverse proxy root.
pub async fn proxy_root_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    proxy_to_upstream(&slug, "").await
}

/// GET /preview/:slug/proxy/*path — reverse proxy subpath.
pub async fn proxy_handler(
    Path((slug, path)): Path<(String, String)>,
) -> Result<Response, (StatusCode, String)> {
    proxy_to_upstream(&slug, path.trim_start_matches('/')).await
}

/// Shared reverse proxy implementation.
async fn proxy_to_upstream(slug: &str, sub_path: &str) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    let port = match &entry.kind {
        PreviewKind::Server { port } => *port,
        PreviewKind::File { .. } => {
            return Err((StatusCode::BAD_REQUEST, "This preview serves a file, not a server.".to_string()));
        }
    };

    let target_url = format!("http://127.0.0.1:{}/{}", port, sub_path);

    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    let upstream = match client.get(&target_url).send().await {
        Ok(resp) => resp,
        Err(e) if e.is_connect() => {
            return Ok(server_not_running_page(port));
        }
        Err(e) => {
            return Err((StatusCode::BAD_GATEWAY, format!("Upstream error: {e}")));
        }
    };

    let status = StatusCode::from_u16(upstream.status().as_u16())
        .unwrap_or(StatusCode::BAD_GATEWAY);

    let mut builder = Response::builder().status(status);
    for key in ["content-type", "content-length", "cache-control"] {
        if let Some(val) = upstream.headers().get(key) {
            builder = builder.header(key, val);
        }
    }

    let body = upstream.bytes().await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("Failed to read upstream body: {e}")))?;

    Ok(builder.body(Body::from(body)).unwrap())
}

fn server_not_running_page(port: u16) -> Response {
    let html = format!(
        r#"<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Server not running</title>
<style>
  body {{ font-family: -apple-system, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #f5f5f5; color: #333; }}
  .card {{ text-align: center; padding: 40px; background: #fff; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); max-width: 400px; }}
  .card h2 {{ margin-bottom: 8px; }}
  .card p {{ color: #666; line-height: 1.5; }}
  .port {{ font-family: monospace; background: #eee; padding: 2px 6px; border-radius: 4px; }}
</style></head>
<body><div class="card">
  <h2>Server not running</h2>
  <p>No server is responding on port <span class="port">{port}</span>.<br>
  The dev server may have stopped or not started yet.</p>
</div></body></html>"#,
        port = port,
    );
    Response::builder()
        .status(StatusCode::BAD_GATEWAY)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap()
}

// ===========================================================================
// Markdown preview — rendered document page
// ===========================================================================

/// GET /md-preview/:slug — read the markdown file and render with marked.js.
pub async fn md_preview_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(&slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    let file_path = match &entry.kind {
        PreviewKind::File { path } => path,
        PreviewKind::Server { .. } => {
            return Err((StatusCode::BAD_REQUEST, "This preview serves a server, not a file.".to_string()));
        }
    };

    let content = tokio::fs::read_to_string(file_path).await.map_err(|e| {
        (StatusCode::INTERNAL_SERVER_ERROR, format!("Failed to read file: {e}"))
    })?;

    let remaining_ms = remaining_millis(&entry);
    let title = escape_html(&entry.title);

    // Escape the markdown for embedding in a JS template literal.
    let escaped_md = content
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${")
        .replace("</script>", "<\\/script>");

    let toolbar = toolbar_and_timer(&title, remaining_ms, "");
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css">
<style>
  {toolbar_css}
  body {{
    background: #fff;
    color: #1f2328;
  }}
  .markdown-body {{
    max-width: 880px;
    margin: 0 auto;
    padding: 32px 24px 64px;
  }}
  @media (max-width: 767px) {{
    .markdown-body {{ padding: 16px; }}
  }}
  .markdown-body pre {{
    background: #f6f8fa;
    border-radius: 6px;
    padding: 16px;
    overflow-x: auto;
  }}
  .markdown-body code {{
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
    font-size: 85%;
  }}
  .markdown-body pre code {{
    background: transparent;
    padding: 0;
  }}
  .markdown-body table {{
    border-collapse: collapse;
    width: 100%;
  }}
  .markdown-body table th,
  .markdown-body table td {{
    border: 1px solid #d0d7de;
    padding: 6px 13px;
  }}
  .markdown-body table tr:nth-child(2n) {{
    background: #f6f8fa;
  }}
</style>
</head>
<body>
{toolbar}
<article class="markdown-body" id="content"></article>
<script src="https://cdn.jsdelivr.net/npm/marked@15/marked.min.js"></script>
<script>
(function() {{
  var raw = `{raw_md}`;
  document.getElementById('content').innerHTML = marked.parse(raw, {{ gfm: true }});
}})();
</script>
</body>
</html>"#,
        title = title,
        toolbar_css = TOOLBAR_CSS,
        toolbar = toolbar,
        raw_md = escaped_md,
    );
    Ok(html_response(html))
}

// ===========================================================================
// Shared utilities
// ===========================================================================

fn remaining_millis(entry: &common::preview_entries::PreviewEntry) -> u128 {
    entry.expires_at
        .saturating_duration_since(std::time::Instant::now())
        .as_millis()
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn html_response(html: String) -> Response {
    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap()
}

/// Toolbar HTML + countdown timer script.
fn toolbar_and_timer(title: &str, remaining_ms: u128, extra_buttons: &str) -> String {
    format!(
        r#"<div class="toolbar">
  <span class="title">{title}</span>
  <span class="badge" id="timer">5:00</span>
  <span class="spacer"></span>
  {extra_buttons}
</div>
<script>
(function() {{
  var expiry = Date.now() + {remaining_ms};
  var el = document.getElementById('timer');
  setInterval(function() {{
    var left = Math.max(0, expiry - Date.now());
    var m = Math.floor(left / 60000);
    var s = Math.floor((left % 60000) / 1000);
    el.textContent = m + ':' + (s < 10 ? '0' : '') + s;
    if (left <= 0) {{
      el.textContent = 'Expired';
      el.style.background = '#6b2020';
      el.style.color = '#e5a5a5';
    }}
  }}, 1000);
}})();
</script>"#,
        title = title,
        remaining_ms = remaining_ms,
        extra_buttons = extra_buttons,
    )
}

/// Toolbar CSS shared by all preview modes.
const TOOLBAR_CSS: &str = r#"
  * { margin: 0; padding: 0; box-sizing: border-box; }
  .toolbar {
    position: sticky;
    top: 0;
    z-index: 100;
    height: 40px;
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 0 16px;
    background: #1a1a1a;
    border-bottom: 1px solid #333;
    font-size: 13px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: #eee;
  }
  .toolbar .title {
    font-weight: 600;
    color: #fff;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .toolbar .badge {
    background: #2d6a4f;
    color: #b7e4c7;
    padding: 2px 8px;
    border-radius: 10px;
    font-size: 11px;
    flex-shrink: 0;
  }
  .toolbar .spacer { flex: 1; }
  .toolbar button {
    background: #333;
    color: #ccc;
    border: 1px solid #444;
    padding: 4px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }
  .toolbar button:hover { background: #444; color: #fff; }
"#;
